### ISSUE TITLE
toast is showing behind the notch

### ISSUE THREAD

**Issue by ddikodroid** [kubilaysalih/react-native-customizable-toast#1]
![Simulator Screen Shot - iPhone 13 - 2022-02-08 at 18 28 28](https://user-images.githubusercontent.com/4207774/152978375-bdcce3e2-0bd2-4f43-8a0a-ea286f0bbee6.png)

**package.json**
```"react": "17.0.2",
    "react-native": "0.67.2",
    "react-native-customizable-toast": "^0.1.7",
    "react-native-gesture-handler": "^2.2.0",
    "react-native-reanimated": "^2.3.1",
    "react-native-safe-area-context": "^3.3.2",
```

**App.js**
```
const App = () => {
  return (
    <SafeAreaProvider>
      <NavigationContainer>
        <StatusBar barStyle="dark-content" />
        <RootNavigation />
        <Toaster />
      </NavigationContainer>
    </SafeAreaProvider>
  );
};
export default gestureHandlerRootHOC(App);
```

**Comment by ddikodroid** [comment]
solution but only for one toast at a time
```
    <Animated.View
        style={[styles,{paddingTop:44}]}
        entering={entering}
        exiting={exiting}
        layout={layout}
        onLayout={onLayout}
     >
        {children}
      </Animated.View>
```

**Comment by kubilaysalih** [comment]
I think we should not use the safe area view and leave it to the developer to handle notch things. In your App.js, you can easily wrap toaster component with safe area view.

`
<SafeAreaView style={StyleSheet.absoluteFillObject} pointerEvents="box-none">
          <Toaster />
        </SafeAreaView>
`

**Comment by ddikodroid** [comment]
> 

 @kubilaysalih  why don't use safe area view? any concern about using it?

**Comment by kubilaysalih** [comment]
Its because maybe the developer would like to have a toast like this. 
https://github.com/lucasferreira/react-native-flash-message

If we change View to Safe Area View, people cant achieve that kind of alert.

**Comment by ddikodroid** [comment]
> I think we should not use the safe area view and leave it to the developer to handle notch things. In your App.js, you can easily wrap toaster component with safe area view.
> 
> `<SafeAreaView style={StyleSheet.absoluteFillObject} pointerEvents="box-none"> <Toaster /> </SafeAreaView>`

ok, so i'll just use this code, thank you!

**Comment by kubilaysalih** [comment]
Thank you for your interest 🥰
